// <auto-generated />
using System;
using MasiveApi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Masive.Infrastructure.Migrations
{
    [DbContext(typeof(MusicaContext))]
    [Migration("20220619010717_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasiveApi.Api.Data.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_Categoria")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__CB903349D4D27532");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_Cliente")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Apellido2")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("IdUsuario")
                        .HasColumnName("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Nombre2")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__3DD0A8CB3B997769");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Detalles", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_Detalle")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodigoFactura")
                        .HasColumnName("Codigo_factura")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnName("Fecha_compra")
                        .HasColumnType("datetime");

                    b.Property<int>("IdProducto")
                        .HasColumnName("Id_Producto")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnName("Precio_total")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle")
                        .HasName("PK__Detalles__9274780B0EBE89C6");

                    b.HasIndex("CodigoFactura");

                    b.HasIndex("IdProducto");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Factura", b =>
                {
                    b.Property<int>("CodigoFactura")
                        .HasColumnName("Codigo_factura")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnName("Id_Cliente")
                        .HasColumnType("int");

                    b.HasKey("CodigoFactura")
                        .HasName("PK__Factura__90794BC07B66CD03");

                    b.HasIndex("IdCliente");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Productos", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_Producto")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCategoria")
                        .HasColumnName("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Precio")
                        .HasColumnName("precio")
                        .HasColumnType("int");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__2085A9CF1F7E32EE");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_Usuario")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__63C76BE2A387BFCD");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Cliente", b =>
                {
                    b.HasOne("MasiveApi.Api.Data.Usuario", "IdUsuarioNavigation")
                        .WithMany("Cliente")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Cliente__Id_Usua__267ABA7A")
                        .IsRequired();
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Detalles", b =>
                {
                    b.HasOne("MasiveApi.Api.Data.Factura", "CodigoFacturaNavigation")
                        .WithMany("Detalles")
                        .HasForeignKey("CodigoFactura")
                        .HasConstraintName("FK__Detalles__Codigo__412EB0B6")
                        .IsRequired();

                    b.HasOne("MasiveApi.Api.Data.Productos", "IdProductoNavigation")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Detalles__Id_Pro__403A8C7D")
                        .IsRequired();
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Factura", b =>
                {
                    b.HasOne("MasiveApi.Api.Data.Cliente", "IdClienteNavigation")
                        .WithMany("Factura")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Factura__Id_Clie__2A4B4B5E")
                        .IsRequired();
                });

            modelBuilder.Entity("MasiveApi.Api.Data.Productos", b =>
                {
                    b.HasOne("MasiveApi.Api.Data.Categoria", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Productos__Id_Ca__398D8EEE")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
